# Generated by Django 4.2.23 on 2025-06-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0004_videobienvenida_remove_presentacion_video_bienvenida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracion',
            name='codigo',
            field=models.CharField(choices=[('adfan', 'Administración de Familias y Niños (ADFAN)'), ('acuden', 'Administración para el Cuidado y Desarrollo Integral de la Niñez (ACUDEN)'), ('adsef', 'Administración de Desarrollo Socioeconómico de la Familia (ADSEF)'), ('asume', 'Administración para el Sustento de Menores (ASUME)'), ('secretariado', 'Secretariado del Departamento de la Familia'), ('ofi de lic.', 'Oficina de Licenciamiento'), ('procurador', 'Programa Estatal del Procurador de Cuidado a Larga Duración'), ('TRUC+', 'Proyecto TRUC+'), ('emergency grant', 'Proyecto Emergency Situation Grant'), ('veterando', 'Procurador del Veterano')], max_length=20, unique=True),
        ),
    ]
