# Generated by Django 4.2.17 on 2025-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
