# Generated by Django 4.2.17 on 2025-02-09 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0003_event_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='table',
        ),
        migrations.AddField(
            model_name='attendee',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
