# Generated by Django 4.1.12 on 2025-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0005_region_attendee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
