# Generated by Django 4.1.12 on 2025-03-19 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0006_attendee_checked_out_attendee_checkout_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='registration_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='attendee',
            name='unique_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ponchapr_app.region'),
        ),
    ]
