# Generated by Django 4.1.12 on 2025-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0007_alter_attendee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
