# Generated by Django 4.1.12 on 2025-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0008_alter_attendee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
