# Generated by Django 4.1.12 on 2025-04-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0010_event_attendee_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('email', 'event')},
        ),
    ]
