# Generated by Django 4.1.12 on 2025-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0011_alter_attendee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
