# Generated by Django 4.1.12 on 2025-04-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0012_alter_attendee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmo', models.CharField(max_length=10)),
                ('office_name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='ponchapr_app.region')),
            ],
            options={
                'ordering': ['office_name'],
            },
        ),
        migrations.AddField(
            model_name='attendee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponchapr_app.localoffice'),
        ),
    ]
