# Generated by Django 4.2.23 on 2025-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponchapr_app', '0013_localoffice_attendee_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='office',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='region',
        ),
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.CharField(default='Sin especificar', max_length=200, verbose_name='Organización/Agencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
