# Generated by Django 4.2.23 on 2025-06-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='evaluacion_acuden',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='evaluacion_adfan',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='evaluacion_adsef',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='evaluacion_asume',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='evaluacion_secretariado',
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='evaluacion_indice_bienestar',
            field=models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Índice de Bienestar de la Niñez y la Juventud'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='evaluacion_panel_bigeneracional',
            field=models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Panel: Iniciativas Bigeneracionales'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='evaluacion_panel_emprender',
            field=models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Panel: Apoyos y Oportunidades para Emprender'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='evaluacion_plan_decenal',
            field=models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Plan Decenal para Combatir la Pobreza Infantil'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='evaluacion_tendencias_laborales',
            field=models.CharField(blank=True, choices=[('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('incompleta', 'Incompleta')], max_length=20, verbose_name='Tendencias Laborales en Puerto Rico'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='comentarios',
            field=models.TextField(help_text='Campo obligatorio: Comparta sus comentarios, sugerencias o solicitudes de información adicional', max_length=1000, verbose_name='Comentarios adicionales'),
        ),
    ]
